service: delivery-pipeline-tutorial-application

provider:
  name: aws
  runtime: python3.7

package:
  exclude:
    - tests/**
    - delivery/**
    - LICENSE
    - README.md

functions:
  helloWorld:
    handler: services.hello_world.hello_world.entry_point
    name: HelloWorld
    description: A lambda function to help us demonstrate continuous delivery
